version: '3.7'

services:
  app:
    image: ntuleaderboardbackend.azurecr.io/image-fyp-ntuleaderboard-backend:latest
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  proxy:
    image: ntuleaderboardbackendproxy.azurecr.io/image-fyp-ntuleaderboard-backend-proxy:latest
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"

volumes:
  static_data: