version: '3.7'

services:
  app:
    image: eduquestbackend.azurecr.io/xeroxis-xs/eduquest-backend-django:latest
    # build:
    #   context: .
    ports:
      - "8000:8000"
    command: gunicorn core.wsgi:application -b 0.0.0.0:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID}
      - AZURE_AD_CLIENT_SECRET=${AZURE_AD_CLIENT_SECRET}