version: '3.8'

services:
  app:
    image: xeroxisxs/eduquest-backend-django:latest
    platform: linux/arm64/v8
    ports:
      - "8000:8000"
    command: sh -c "python manage.py collectstatic --noinput && gunicorn core.wsgi:application -b 0.0.0.0:8000"
    environment:
      - REDIS_HOST=redis
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID}
      - AZURE_AD_CLIENT_SECRET=${AZURE_AD_CLIENT_SECRET}
      - AZURE_ACCOUNT_NAME=${AZURE_ACCOUNT_NAME}
      - AZURE_ACCOUNT_KEY=${AZURE_ACCOUNT_KEY}
      - AZURE_CONTAINER=${AZURE_CONTAINER}
      - AZURE_STORAGE_ACCOUNT_CONNECTION_STRING=${AZURE_STORAGE_ACCOUNT_CONNECTION_STRING}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0  # Added

  celery:
    image: xeroxisxs/eduquest-backend-django:latest
    platform: linux/arm64/v8
    command: celery -A core worker --loglevel=info
    environment:
      - REDIS_HOST=redis
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID}
      - AZURE_AD_CLIENT_SECRET=${AZURE_AD_CLIENT_SECRET}
      - AZURE_ACCOUNT_NAME=${AZURE_ACCOUNT_NAME}
      - AZURE_ACCOUNT_KEY=${AZURE_ACCOUNT_KEY}
      - AZURE_CONTAINER=${AZURE_CONTAINER}
      - AZURE_STORAGE_ACCOUNT_CONNECTION_STRING=${AZURE_STORAGE_ACCOUNT_CONNECTION_STRING}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0  # Added

  celery-beat:
    image: xeroxisxs/eduquest-backend-django:latest
    platform: linux/arm64/v8
    command: celery -A core beat --loglevel=info
    environment:
      - REDIS_HOST=redis
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID}
      - AZURE_AD_CLIENT_SECRET=${AZURE_AD_CLIENT_SECRET}
      - AZURE_ACCOUNT_NAME=${AZURE_ACCOUNT_NAME}
      - AZURE_ACCOUNT_KEY=${AZURE_ACCOUNT_KEY}
      - AZURE_CONTAINER=${AZURE_CONTAINER}
      - AZURE_STORAGE_ACCOUNT_CONNECTION_STRING=${AZURE_STORAGE_ACCOUNT_CONNECTION_STRING}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0  # Added

  redis:
    image: "redis:alpine"
    platform: linux/arm64/v8
    ports:
      - "6379:6379"
