from django.urls import path, re_path
from .views import (
    EduquestUserListCreateView,
    EduquestUserManageView,
    AcademicYearListCreateView,
    AcademicYearManageView,
    TermListCreateView,
    TermManageView,
    CourseListCreateView,
    CourseManageView,
    CourseByTermView,
    QuestListCreateView,
    QuestManageView,
    QuestByCourseView,
    QuestionListCreateView,
    QuestionManageView,
    QuestionByQuestView,
    AnswerListCreateView,
    AnswerManageView,
    AnswerByQuestView,
    UserQuestAttemptListCreateView,
    UserQuestAttemptManageView,
    UserQuestQuestionAttemptListCreateView,
    UserQuestQuestionAttemptManageView,
    UserCourseCompletionListCreateView,
    UserCourseCompletionManageView,
    BadgeListCreateView,
    BadgeManageView,
)

urlpatterns = [
    path("EduquestUser/", EduquestUserListCreateView.as_view(), name='EduquestUser-list-create'),
    path("EduquestUser/<str:email>/", EduquestUserManageView.as_view(), name='EduquestUser-retrieve-update-destroy'),
    path("AcademicYear/", AcademicYearListCreateView.as_view(), name='AcademicYear-list-create'),
    path("AcademicYear/<int:pk>/", AcademicYearManageView.as_view(), name='AcademicYear-retrieve-update-destroy'),
    path("Term/", TermListCreateView.as_view(), name='Term-list-create'),
    path("Term/<int:pk>/", TermManageView.as_view(), name='Term-retrieve-update-destroy'),
    path("Course/", CourseListCreateView.as_view(), name='Course-list-create'),
    path("Course/<int:pk>/", CourseManageView.as_view(), name='Course-retrieve-update-destroy'),
    path("Course/by-term/<int:term_id>/", CourseByTermView.as_view(), name='Course-by-term'),
    path("Quest/", QuestListCreateView.as_view(), name='Quest-list-create'),
    path("Quest/<int:pk>/", QuestManageView.as_view(), name='Quest-retrieve-update-destroy'),
    path("Quest/by-course/<int:course_id>/", QuestByCourseView.as_view(), name='Quest-by-course'),
    path("Question/", QuestionListCreateView.as_view(), name='Question-list-create'),
    path("Question/<int:pk>/", QuestionManageView.as_view(), name='Question-retrieve-update-destroy'),
    path("Question/by-quest/<int:quest_id>/", QuestionByQuestView.as_view(), name='Question-by-quest'),
    path("Answer/", AnswerListCreateView.as_view(), name='Answer-list-create'),
    path("Answer/<int:pk>/", AnswerManageView.as_view(), name='Answer-retrieve-update-destroy'),
    path("Answer/by-quest/<int:quest_id>/", AnswerByQuestView.as_view(), name='Answer-by-quest'),

    path("UserQuestAttempt/", UserQuestAttemptListCreateView.as_view(), name='UserQuestAttempt-list-create'),
    path("UserQuestAttempt/<int:pk>/", UserQuestAttemptManageView.as_view(), name='UserQuestAttempt-retrieve-update-destroy'),
    path("UserQuestQuestionAttempt/", UserQuestQuestionAttemptListCreateView.as_view(), name='UserQuestQuestionAttempt-list-create'),
    path("UserQuestQuestionAttempt/<int:pk>/", UserQuestQuestionAttemptManageView.as_view(), name='UserQuestQuestionAttempt-retrieve-update-destroy'),
    path("UserCourseCompletion/", UserCourseCompletionListCreateView.as_view(), name='UserCourseCompletion-list-create'),
    path("UserCourseCompletion/<int:pk>/", UserCourseCompletionManageView.as_view(), name='UserCourseCompletion-retrieve-update-destroy'),
    path("Badge/", BadgeListCreateView.as_view(), name='Badge-list-create'),
    path("Badge/<int:pk>/", BadgeManageView.as_view(), name='Badge-retrieve-update-destroy'),
]
