# Generated by Django 5.0.6 on 2024-07-12 10:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attemptanswerrecord',
            old_name='selected_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='userquestattempt',
            old_name='is_first_attempt',
            new_name='graded',
        ),
        migrations.RemoveField(
            model_name='userquestattempt',
            name='is_perfect_score',
        ),
        migrations.RemoveField(
            model_name='userquestquestionattempt',
            name='attempted_on',
        ),
        migrations.RemoveField(
            model_name='userquestquestionattempt',
            name='score',
        ),
        migrations.RemoveField(
            model_name='userquestquestionattempt',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='userquestattempt',
            name='time_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestquestionattempt',
            name='score_achieved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attemptanswerrecord',
            name='user_quest_question_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_answers', to='api.userquestquestionattempt'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_score',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userquestattempt',
            name='first_attempted_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 12, 18, 12, 27, 865712)),
            preserve_default=False,
        ),
    ]
