# Generated by Django 5.0.6 on 2024-09-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduquestuser',
            name='courses_coordinated',
            field=models.ManyToManyField(related_name='coordinators_of', to='api.course'),
        ),
    ]
