# Generated by Django 5.0.6 on 2024-07-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestattempt',
            name='last_attempted_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
