# Generated by Django 5.0.6 on 2024-09-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestattempt',
            old_name='user',
            new_name='student',
        ),
    ]
