# Generated by Django 5.0.6 on 2024-07-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userquestattempt_last_attempted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestattempt',
            name='last_attempted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
