# Generated by Django 5.0.6 on 2024-09-14 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_userquestattempt_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestquestionattempt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userquestquestionattempt',
            name='user_quest_attempt',
        ),
        migrations.CreateModel(
            name='UserAnswerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('score_achieved', models.FloatField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('user_quest_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_attempts', to='api.userquestattempt')),
            ],
        ),
        migrations.DeleteModel(
            name='AttemptAnswerRecord',
        ),
        migrations.DeleteModel(
            name='UserQuestQuestionAttempt',
        ),
    ]
