# Generated by Django 5.0.6 on 2024-07-08 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_course_total_quests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='quests_participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
