# Generated by Django 5.0.6 on 2024-07-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_selected_answer_attemptanswerrecord_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptanswerrecord',
            name='is_correct',
        ),
    ]
