# Generated by Django 5.0.6 on 2024-09-14 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userquestquestionattempt_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestattempt',
            old_name='all_questions_submitted',
            new_name='submitted',
        ),
        migrations.AlterField(
            model_name='useranswerattempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer_attempts', to='api.question'),
        ),
    ]
