# Generated by Django 5.0.6 on 2024-09-13 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_eduquestuser_courses_coordinated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='group',
        ),
    ]
