# Generated by Django 5.0.6 on 2024-07-09 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_quest_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='participants',
        ),
    ]
