# Generated by Django 5.0.6 on 2024-07-27 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userquestattempt_last_attempted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursebadge',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image'),
        ),
        migrations.AddField(
            model_name='userquestbadge',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image'),
        ),
        migrations.AlterField(
            model_name='userquestattempt',
            name='last_attempted_on',
            field=models.DateTimeField(),
        ),
    ]
