# Generated by Django 5.0.6 on 2024-07-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_attemptanswerrecord_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswerrecord',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
