# Generated by Django 5.0.6 on 2024-09-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_all_questions_submitted_userquestattempt_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='tutorial_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
