# Generated by Django 5.0.6 on 2024-09-13 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_course_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoursegroupenrollment',
            name='user',
        ),
        migrations.AddField(
            model_name='usercoursegroupenrollment',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercoursegroupenrollment',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='api.coursegroup'),
        ),
    ]
