# Generated by Django 5.0.6 on 2024-07-27 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usercoursebadge_image_userquestbadge_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoursebadge',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userquestbadge',
            name='image',
        ),
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image'),
        ),
    ]
