# Generated by Django 5.0.6 on 2024-07-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attemptanswerrecord_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestquestionattempt',
            name='score_achieved',
            field=models.FloatField(default=0),
        ),
    ]
