# Generated by Django 5.0.6 on 2024-09-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_quest_tutorial_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestbadge',
            old_name='quest_attempted',
            new_name='user_quest_attempt',
        ),
    ]
