# Generated by Django 5.0.6 on 2024-09-13 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_usercoursegroupenrollment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='from_course_group',
            new_name='course_group',
        ),
    ]
