# Generated by Django 5.0.6 on 2024-07-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_usercoursebadge_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='expired_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
