# Generated by Django 5.0.6 on 2024-07-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_quest_expired_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='expired_on',
            new_name='expiration_date',
        ),
    ]
