# Generated by Django 5.0.6 on 2024-07-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_graded_userquestattempt_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestquestionattempt',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
