# Generated by Django 5.0.6 on 2024-09-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usercoursegroupenrollment_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='tutorial_date',
        ),
    ]
