# Generated by Django 5.0.6 on 2024-07-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userquestquestionattempt_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestattempt',
            name='total_score_achieved',
            field=models.FloatField(default=0),
        ),
    ]
