# Generated by Django 5.0.6 on 2024-07-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userquestattempt_total_score_achieved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestattempt',
            name='total_score_achieved',
        ),
    ]
