# Generated by Django 5.0.6 on 2024-07-17 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_image_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image'),
        ),
    ]
