# Generated by Django 5.0.6 on 2024-07-18 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_quest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
