# Generated by Django 5.0.6 on 2024-08-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_quest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
