# Generated by Django 5.0.6 on 2024-08-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_course_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestattempt',
            name='first_attempted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userquestattempt',
            name='last_attempted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
