# Generated by Django 5.0.6 on 2024-08-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_userquestattempt_first_attempted_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduquestuser',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
