# Generated by Django 5.0.6 on 2024-07-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_eduquestuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
