# Generated by Django 5.0.6 on 2024-08-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_eduquestuser_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduquestuser',
            name='total_points',
            field=models.FloatField(default=0),
        ),
    ]
