# Generated by Django 5.0.6 on 2024-08-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_eduquestuser_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestattempt',
            name='total_score_achieved',
            field=models.FloatField(default=0),
        ),
    ]
